version: '3.8'

services:
  ktor-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - python-server

  python-server:
    build:
      context: ./detection
      dockerfile: Dockerfile
    ports:
      - "1234:1234"